from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<uidb64>/<token>/', views.reset_password, name='reset_password'),
    path('admin-panel/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-panel/students/', views.student_management, name='student_management'),
    path('admin-panel/students/<int:student_id>/edit/', views.edit_student, name='edit_student'),
    path('admin-panel/students/<int:student_id>/delete/', views.delete_student, name='delete_student'),
    path('admin-panel/attendance/mark/', views.mark_attendance, name='mark_attendance'),
    path('admin-panel/attendance/export/', views.export_attendance, name='export_attendance'),
    path('admin-panel/attendance/analytics/', views.attendance_analytics, name='attendance_analytics'),
    path('admin-panel/news/', views.manage_news, name='manage_news'),
    path('admin-panel/news/<int:news_id>/', views.news_detail, name='news_detail'),
    path('admin-panel/news/<int:news_id>/update/', views.update_news, name='update_news'),
    path('admin-panel/news/<int:news_id>/delete/', views.delete_news, name='delete_news'),
    path('admin-panel/leave-requests/', views.manage_leave_requests, name='manage_leave_requests'),
    path('admin-panel/student/dashboard/', views.student_dashboard, name='student_dashboard'),
    path('admin-panel/student/profile/', views.student_profile, name='student_profile'),
    path('admin-panel/student/settings/', views.student_settings, name='student_settings'),
    path('admin-panel/student/leave-request/', views.student_leave_request, name='student_leave_request'),
    path('admin-panel/student/news/', views.student_news, name='student_news'),
    path('admin-panel/student/attendance-report/', views.download_attendance_report, name='download_attendance_report'),
    path('admin-panel/notifications/mark-read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('admin-panel/profile/', views.admin_profile, name='admin_profile'),
    path('admin-panel/settings/', views.admin_settings, name='admin_settings'),
    path('admin-panel/change-password/', views.change_password, name='change_password'),
    path('admin-panel/update-notification-settings/', views.update_notification_settings, name='update_notification_settings'),
    path('admin-panel/update-privacy-settings/', views.update_privacy_settings, name='update_privacy_settings'),
    path('admin/student/delete/<int:student_id>/', views.delete_student, name='delete_student'),
    path('admin/student/quick-edit/', views.quick_edit_student, name='quick_edit_student'),
]