# Generated by Django 5.2 on 2025-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_core', '0003_remove_studentprofile_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Parent's Phone Number"),
        ),
    ]
